// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvakmssweququzzespuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2YWttc3N3ZXF1cXV6emVzcHV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDE4MzAsImV4cCI6MjA3MDgxNzgzMH0.ykW-cFwMCXz_K_kK1H6zq7VN7Mn_34oxYzYpZRo-44k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});